name: Automated Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_resha.py

      - name: Commit processed data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add preprocessing/preprocessed/* 
          if ! git diff-index --quiet HEAD; then
            echo "Ada perubahan pada dataset, melakukan commit dan push..."
            git commit -m 'Berhasil update dataset [automated]'
            git push
          else
            echo "Tidak ada perubahan pada dataset, melewati commit."
          fi
